# docker run --name api-find-a-friend-rocketseat -pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL-DATABASE=find-a-friend -p 5432:5432  bitnami/postgressql


version: '3'

services:
  api-find-a-friend-rocketseat:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=find-a-friend